#!/bin/bash
set -e
userdel -r lehrer
userdel -r seminar
userdel -r k1am
userdel -r k1bm
userdel -r k1cm
userdel -r k2am
userdel -r k2bm
userdel -r k2cm
userdel -r k3am
userdel -r k3bm
userdel -r k3cm
userdel -r k4am
userdel -r k4bm
userdel -r k4cm
userdel -r k5am
userdel -r k5bm
userdel -r k5cm
userdel -r k1af
userdel -r k1bf
userdel -r k1cf
userdel -r k2af
userdel -r k2bf
userdel -r k3afi
userdel -r k3bfn
userdel -r k4afi
userdel -r k4bfn
userdel -r k1ai
userdel -r k1bi
userdel -r k1ci
userdel -r k2ai
userdel -r k2bi
userdel -r k2ci
userdel -r k3ai
userdel -r k3bi
userdel -r k3ci
userdel -r k4ai
userdel -r k4bi
userdel -r k4cn
userdel -r k5ax
userdel -r k5bi
userdel -r k5cn
userdel -r k1ao
