#!/bin/bash
set -e
userdel -r maximilian_de_junious
userdel -r ramon_nunez_gomez
userdel -r ulku_omer_ullagoss
userdel -r isis_lanpher
userdel -r maximilian_galvin
userdel -r jannette_laspina
userdel -r marg_dodich
userdel -r carisa_bannowsky
userdel -r david_waisath
userdel -r paulette_von_reddigpiette
userdel -r kirby_latona
userdel -r reed_homewood
userdel -r blair_pallaforzedian
userdel -r lon_senemounnaratquillian
userdel -r vada_isaac
userdel -r jeanett_plancarte
userdel -r alex_berteottistirn
userdel -r robyn_strycker
userdel -r camille_von_verrill
userdel -r franz_michael_leopold_deschner
userdel -r veola_franzi
userdel -r chantelle_cringle
userdel -r britney_kosh
userdel -r clayton_derouchie
userdel -r beverlee_doutt
userdel -r alma_munley
userdel -r thad_dornbos
userdel -r arvilla_mahala
userdel -r mirza_ellingwood
userdel -r francie_de_cardinallisciola
userdel -r irenee_gundry
userdel -r irenee_pinedo
userdel -r chelah_faivre
userdel -r mirza_pinsky
userdel -r francie_pinsky1
userdel -r goldie_pinsky2
userdel -r another_pinsky3
userdel -r andromede_norlien
userdel -r helaah_preato
